// flow-typed signature: 9a2617c76122da2097429b91bac6216a
// flow-typed version: <<STUB>>/babel-preset-stage-0_v6.3.x/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-stage-0'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-stage-0' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-stage-0/index' {
  declare module.exports: $Exports<'babel-preset-stage-0'>;
}
declare module 'babel-preset-stage-0/index.js' {
  declare module.exports: $Exports<'babel-preset-stage-0'>;
}
