// flow-typed signature: 94790f3accf8e47677c55cc7d7aabb7f
// flow-typed version: <<STUB>>/babel-plugin-transform-es2015-modules-amd_v6.3.x

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-es2015-modules-amd'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-es2015-modules-amd' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-es2015-modules-amd/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-es2015-modules-amd/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-es2015-modules-amd/lib/index'>;
}
