// flow-typed signature: 22e48a9bd63d8108db2b603d617bfa12
// flow-typed version: <<STUB>>/babel-preset-es2015_v6.3.x

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-es2015'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-es2015' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-es2015/index' {
  declare module.exports: $Exports<'babel-preset-es2015'>;
}
declare module 'babel-preset-es2015/index.js' {
  declare module.exports: $Exports<'babel-preset-es2015'>;
}
