// flow-typed signature: 84283fa2a931ba811d1f89f42e6fc2ca
// flow-typed version: <<STUB>>/handlebars_v^4.0.5/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'handlebars'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'handlebars' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'handlebars/dist/amd/handlebars' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars.runtime' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars/base' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars/compiler/ast' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars/compiler/base' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars/compiler/code-gen' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars/compiler/compiler' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars/compiler/helpers' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars/compiler/javascript-compiler' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars/compiler/parser' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars/compiler/printer' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars/compiler/visitor' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars/compiler/whitespace-control' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars/decorators' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars/decorators/inline' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars/exception' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars/helpers' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars/helpers/block-helper-missing' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars/helpers/each' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars/helpers/helper-missing' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars/helpers/if' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars/helpers/log' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars/helpers/lookup' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars/helpers/with' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars/logger' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars/no-conflict' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars/runtime' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars/safe-string' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars/utils' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/precompiler' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars.runtime' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars/base' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars/compiler/ast' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars/compiler/base' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars/compiler/code-gen' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars/compiler/compiler' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars/compiler/helpers' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars/compiler/javascript-compiler' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars/compiler/parser' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars/compiler/printer' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars/compiler/visitor' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars/compiler/whitespace-control' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars/decorators' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars/decorators/inline' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars/exception' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars/helpers' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars/helpers/block-helper-missing' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars/helpers/each' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars/helpers/helper-missing' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars/helpers/if' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars/helpers/log' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars/helpers/lookup' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars/helpers/with' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars/logger' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars/no-conflict' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars/runtime' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars/safe-string' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars/utils' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/precompiler' {
  declare module.exports: any;
}

declare module 'handlebars/dist/handlebars.amd' {
  declare module.exports: any;
}

declare module 'handlebars/dist/handlebars.amd.min' {
  declare module.exports: any;
}

declare module 'handlebars/dist/handlebars' {
  declare module.exports: any;
}

declare module 'handlebars/dist/handlebars.min' {
  declare module.exports: any;
}

declare module 'handlebars/dist/handlebars.runtime.amd' {
  declare module.exports: any;
}

declare module 'handlebars/dist/handlebars.runtime.amd.min' {
  declare module.exports: any;
}

declare module 'handlebars/dist/handlebars.runtime' {
  declare module.exports: any;
}

declare module 'handlebars/dist/handlebars.runtime.min' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars.runtime' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars/base' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars/compiler/ast' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars/compiler/base' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars/compiler/code-gen' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars/compiler/compiler' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars/compiler/helpers' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars/compiler/javascript-compiler' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars/compiler/parser' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars/compiler/printer' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars/compiler/visitor' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars/compiler/whitespace-control' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars/decorators' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars/decorators/inline' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars/exception' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars/helpers' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars/helpers/block-helper-missing' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars/helpers/each' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars/helpers/helper-missing' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars/helpers/if' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars/helpers/log' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars/helpers/lookup' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars/helpers/with' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars/logger' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars/no-conflict' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars/runtime' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars/safe-string' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars/utils' {
  declare module.exports: any;
}

declare module 'handlebars/lib/index' {
  declare module.exports: any;
}

declare module 'handlebars/lib/precompiler' {
  declare module.exports: any;
}

declare module 'handlebars/runtime' {
  declare module.exports: any;
}

// Filename aliases
declare module 'handlebars/dist/amd/handlebars.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars'>;
}
declare module 'handlebars/dist/amd/handlebars.runtime.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars.runtime'>;
}
declare module 'handlebars/dist/amd/handlebars/base.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars/base'>;
}
declare module 'handlebars/dist/amd/handlebars/compiler/ast.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars/compiler/ast'>;
}
declare module 'handlebars/dist/amd/handlebars/compiler/base.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars/compiler/base'>;
}
declare module 'handlebars/dist/amd/handlebars/compiler/code-gen.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars/compiler/code-gen'>;
}
declare module 'handlebars/dist/amd/handlebars/compiler/compiler.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars/compiler/compiler'>;
}
declare module 'handlebars/dist/amd/handlebars/compiler/helpers.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars/compiler/helpers'>;
}
declare module 'handlebars/dist/amd/handlebars/compiler/javascript-compiler.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars/compiler/javascript-compiler'>;
}
declare module 'handlebars/dist/amd/handlebars/compiler/parser.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars/compiler/parser'>;
}
declare module 'handlebars/dist/amd/handlebars/compiler/printer.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars/compiler/printer'>;
}
declare module 'handlebars/dist/amd/handlebars/compiler/visitor.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars/compiler/visitor'>;
}
declare module 'handlebars/dist/amd/handlebars/compiler/whitespace-control.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars/compiler/whitespace-control'>;
}
declare module 'handlebars/dist/amd/handlebars/decorators.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars/decorators'>;
}
declare module 'handlebars/dist/amd/handlebars/decorators/inline.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars/decorators/inline'>;
}
declare module 'handlebars/dist/amd/handlebars/exception.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars/exception'>;
}
declare module 'handlebars/dist/amd/handlebars/helpers.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars/helpers'>;
}
declare module 'handlebars/dist/amd/handlebars/helpers/block-helper-missing.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars/helpers/block-helper-missing'>;
}
declare module 'handlebars/dist/amd/handlebars/helpers/each.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars/helpers/each'>;
}
declare module 'handlebars/dist/amd/handlebars/helpers/helper-missing.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars/helpers/helper-missing'>;
}
declare module 'handlebars/dist/amd/handlebars/helpers/if.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars/helpers/if'>;
}
declare module 'handlebars/dist/amd/handlebars/helpers/log.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars/helpers/log'>;
}
declare module 'handlebars/dist/amd/handlebars/helpers/lookup.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars/helpers/lookup'>;
}
declare module 'handlebars/dist/amd/handlebars/helpers/with.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars/helpers/with'>;
}
declare module 'handlebars/dist/amd/handlebars/logger.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars/logger'>;
}
declare module 'handlebars/dist/amd/handlebars/no-conflict.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars/no-conflict'>;
}
declare module 'handlebars/dist/amd/handlebars/runtime.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars/runtime'>;
}
declare module 'handlebars/dist/amd/handlebars/safe-string.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars/safe-string'>;
}
declare module 'handlebars/dist/amd/handlebars/utils.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars/utils'>;
}
declare module 'handlebars/dist/amd/precompiler.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/precompiler'>;
}
declare module 'handlebars/dist/cjs/handlebars.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars'>;
}
declare module 'handlebars/dist/cjs/handlebars.runtime.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars.runtime'>;
}
declare module 'handlebars/dist/cjs/handlebars/base.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars/base'>;
}
declare module 'handlebars/dist/cjs/handlebars/compiler/ast.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars/compiler/ast'>;
}
declare module 'handlebars/dist/cjs/handlebars/compiler/base.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars/compiler/base'>;
}
declare module 'handlebars/dist/cjs/handlebars/compiler/code-gen.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars/compiler/code-gen'>;
}
declare module 'handlebars/dist/cjs/handlebars/compiler/compiler.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars/compiler/compiler'>;
}
declare module 'handlebars/dist/cjs/handlebars/compiler/helpers.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars/compiler/helpers'>;
}
declare module 'handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars/compiler/javascript-compiler'>;
}
declare module 'handlebars/dist/cjs/handlebars/compiler/parser.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars/compiler/parser'>;
}
declare module 'handlebars/dist/cjs/handlebars/compiler/printer.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars/compiler/printer'>;
}
declare module 'handlebars/dist/cjs/handlebars/compiler/visitor.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars/compiler/visitor'>;
}
declare module 'handlebars/dist/cjs/handlebars/compiler/whitespace-control.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars/compiler/whitespace-control'>;
}
declare module 'handlebars/dist/cjs/handlebars/decorators.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars/decorators'>;
}
declare module 'handlebars/dist/cjs/handlebars/decorators/inline.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars/decorators/inline'>;
}
declare module 'handlebars/dist/cjs/handlebars/exception.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars/exception'>;
}
declare module 'handlebars/dist/cjs/handlebars/helpers.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars/helpers'>;
}
declare module 'handlebars/dist/cjs/handlebars/helpers/block-helper-missing.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars/helpers/block-helper-missing'>;
}
declare module 'handlebars/dist/cjs/handlebars/helpers/each.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars/helpers/each'>;
}
declare module 'handlebars/dist/cjs/handlebars/helpers/helper-missing.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars/helpers/helper-missing'>;
}
declare module 'handlebars/dist/cjs/handlebars/helpers/if.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars/helpers/if'>;
}
declare module 'handlebars/dist/cjs/handlebars/helpers/log.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars/helpers/log'>;
}
declare module 'handlebars/dist/cjs/handlebars/helpers/lookup.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars/helpers/lookup'>;
}
declare module 'handlebars/dist/cjs/handlebars/helpers/with.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars/helpers/with'>;
}
declare module 'handlebars/dist/cjs/handlebars/logger.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars/logger'>;
}
declare module 'handlebars/dist/cjs/handlebars/no-conflict.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars/no-conflict'>;
}
declare module 'handlebars/dist/cjs/handlebars/runtime.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars/runtime'>;
}
declare module 'handlebars/dist/cjs/handlebars/safe-string.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars/safe-string'>;
}
declare module 'handlebars/dist/cjs/handlebars/utils.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars/utils'>;
}
declare module 'handlebars/dist/cjs/precompiler.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/precompiler'>;
}
declare module 'handlebars/dist/handlebars.amd.js' {
  declare module.exports: $Exports<'handlebars/dist/handlebars.amd'>;
}
declare module 'handlebars/dist/handlebars.amd.min.js' {
  declare module.exports: $Exports<'handlebars/dist/handlebars.amd.min'>;
}
declare module 'handlebars/dist/handlebars.js' {
  declare module.exports: $Exports<'handlebars/dist/handlebars'>;
}
declare module 'handlebars/dist/handlebars.min.js' {
  declare module.exports: $Exports<'handlebars/dist/handlebars.min'>;
}
declare module 'handlebars/dist/handlebars.runtime.amd.js' {
  declare module.exports: $Exports<'handlebars/dist/handlebars.runtime.amd'>;
}
declare module 'handlebars/dist/handlebars.runtime.amd.min.js' {
  declare module.exports: $Exports<'handlebars/dist/handlebars.runtime.amd.min'>;
}
declare module 'handlebars/dist/handlebars.runtime.js' {
  declare module.exports: $Exports<'handlebars/dist/handlebars.runtime'>;
}
declare module 'handlebars/dist/handlebars.runtime.min.js' {
  declare module.exports: $Exports<'handlebars/dist/handlebars.runtime.min'>;
}
declare module 'handlebars/lib/handlebars.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars'>;
}
declare module 'handlebars/lib/handlebars.runtime.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars.runtime'>;
}
declare module 'handlebars/lib/handlebars/base.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars/base'>;
}
declare module 'handlebars/lib/handlebars/compiler/ast.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars/compiler/ast'>;
}
declare module 'handlebars/lib/handlebars/compiler/base.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars/compiler/base'>;
}
declare module 'handlebars/lib/handlebars/compiler/code-gen.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars/compiler/code-gen'>;
}
declare module 'handlebars/lib/handlebars/compiler/compiler.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars/compiler/compiler'>;
}
declare module 'handlebars/lib/handlebars/compiler/helpers.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars/compiler/helpers'>;
}
declare module 'handlebars/lib/handlebars/compiler/javascript-compiler.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars/compiler/javascript-compiler'>;
}
declare module 'handlebars/lib/handlebars/compiler/parser.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars/compiler/parser'>;
}
declare module 'handlebars/lib/handlebars/compiler/printer.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars/compiler/printer'>;
}
declare module 'handlebars/lib/handlebars/compiler/visitor.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars/compiler/visitor'>;
}
declare module 'handlebars/lib/handlebars/compiler/whitespace-control.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars/compiler/whitespace-control'>;
}
declare module 'handlebars/lib/handlebars/decorators.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars/decorators'>;
}
declare module 'handlebars/lib/handlebars/decorators/inline.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars/decorators/inline'>;
}
declare module 'handlebars/lib/handlebars/exception.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars/exception'>;
}
declare module 'handlebars/lib/handlebars/helpers.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars/helpers'>;
}
declare module 'handlebars/lib/handlebars/helpers/block-helper-missing.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars/helpers/block-helper-missing'>;
}
declare module 'handlebars/lib/handlebars/helpers/each.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars/helpers/each'>;
}
declare module 'handlebars/lib/handlebars/helpers/helper-missing.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars/helpers/helper-missing'>;
}
declare module 'handlebars/lib/handlebars/helpers/if.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars/helpers/if'>;
}
declare module 'handlebars/lib/handlebars/helpers/log.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars/helpers/log'>;
}
declare module 'handlebars/lib/handlebars/helpers/lookup.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars/helpers/lookup'>;
}
declare module 'handlebars/lib/handlebars/helpers/with.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars/helpers/with'>;
}
declare module 'handlebars/lib/handlebars/logger.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars/logger'>;
}
declare module 'handlebars/lib/handlebars/no-conflict.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars/no-conflict'>;
}
declare module 'handlebars/lib/handlebars/runtime.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars/runtime'>;
}
declare module 'handlebars/lib/handlebars/safe-string.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars/safe-string'>;
}
declare module 'handlebars/lib/handlebars/utils.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars/utils'>;
}
declare module 'handlebars/lib/index.js' {
  declare module.exports: $Exports<'handlebars/lib/index'>;
}
declare module 'handlebars/lib/precompiler.js' {
  declare module.exports: $Exports<'handlebars/lib/precompiler'>;
}
declare module 'handlebars/runtime.js' {
  declare module.exports: $Exports<'handlebars/runtime'>;
}
