// flow-typed signature: c8bad5e84f8c92d583ee987704eb4630
// flow-typed version: <<STUB>>/less_v1.7.x/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'less'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'less' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'less/benchmark/less-benchmark' {
  declare module.exports: any;
}

declare module 'less/build/amd' {
  declare module.exports: any;
}

declare module 'less/build/browser-header' {
  declare module.exports: any;
}

declare module 'less/build/require-rhino' {
  declare module.exports: any;
}

declare module 'less/build/require' {
  declare module.exports: any;
}

declare module 'less/build/rhino-header' {
  declare module.exports: any;
}

declare module 'less/build/rhino-modules' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.1.0' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.1.0.min' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.1.1' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.1.1.min' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.1.2' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.1.2.min' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.1.3' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.1.3.min' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.1.4' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.1.4.min' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.1.5' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.1.5.min' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.1.6' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.1.6.min' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.2.0' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.2.0.min' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.2.1' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.2.1.min' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.2.2' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.2.2.min' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.3.0' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.3.0.min' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.3.1' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.3.1.min' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.3.2' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.3.2.min' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.3.3' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.3.3.min' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.4.0-beta' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.4.0-beta.min' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.4.0' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.4.0.min' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.4.1' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.4.1.min' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.4.2' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.4.2.min' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.5.0' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.5.0.min' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.5.1' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.5.1.min' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.6.0' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.6.0.min' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.6.1' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.6.1.min' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.6.2' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.6.2.min' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.6.3' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.6.3.min' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.7.0' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.7.0.min' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.7.1' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.7.1.min' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.7.2' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.7.2.min' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.7.3' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.7.3.min' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.7.4' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.7.4.min' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.7.5' {
  declare module.exports: any;
}

declare module 'less/dist/less-1.7.5.min' {
  declare module.exports: any;
}

declare module 'less/dist/less-rhino-1.1.3' {
  declare module.exports: any;
}

declare module 'less/dist/less-rhino-1.1.5' {
  declare module.exports: any;
}

declare module 'less/dist/less-rhino-1.3.1' {
  declare module.exports: any;
}

declare module 'less/dist/less-rhino-1.3.2' {
  declare module.exports: any;
}

declare module 'less/dist/less-rhino-1.3.3' {
  declare module.exports: any;
}

declare module 'less/dist/less-rhino-1.4.0' {
  declare module.exports: any;
}

declare module 'less/dist/less-rhino-1.5.1' {
  declare module.exports: any;
}

declare module 'less/dist/less-rhino-1.6.2' {
  declare module.exports: any;
}

declare module 'less/dist/less-rhino-1.6.3' {
  declare module.exports: any;
}

declare module 'less/dist/less-rhino-1.7.0' {
  declare module.exports: any;
}

declare module 'less/dist/less-rhino-1.7.1' {
  declare module.exports: any;
}

declare module 'less/dist/less-rhino-1.7.2' {
  declare module.exports: any;
}

declare module 'less/dist/less-rhino-1.7.3' {
  declare module.exports: any;
}

declare module 'less/dist/less-rhino-1.7.4' {
  declare module.exports: any;
}

declare module 'less/dist/less-rhino-1.7.5' {
  declare module.exports: any;
}

declare module 'less/dist/lessc-rhino-1.6.2' {
  declare module.exports: any;
}

declare module 'less/dist/lessc-rhino-1.6.3' {
  declare module.exports: any;
}

declare module 'less/dist/lessc-rhino-1.7.0' {
  declare module.exports: any;
}

declare module 'less/dist/lessc-rhino-1.7.1' {
  declare module.exports: any;
}

declare module 'less/dist/lessc-rhino-1.7.2' {
  declare module.exports: any;
}

declare module 'less/dist/lessc-rhino-1.7.3' {
  declare module.exports: any;
}

declare module 'less/dist/lessc-rhino-1.7.4' {
  declare module.exports: any;
}

declare module 'less/dist/lessc-rhino-1.7.5' {
  declare module.exports: any;
}

declare module 'less/Gruntfile' {
  declare module.exports: any;
}

declare module 'less/lib/less/browser' {
  declare module.exports: any;
}

declare module 'less/lib/less/colors' {
  declare module.exports: any;
}

declare module 'less/lib/less/encoder' {
  declare module.exports: any;
}

declare module 'less/lib/less/env' {
  declare module.exports: any;
}

declare module 'less/lib/less/extend-visitor' {
  declare module.exports: any;
}

declare module 'less/lib/less/fs' {
  declare module.exports: any;
}

declare module 'less/lib/less/functions' {
  declare module.exports: any;
}

declare module 'less/lib/less/import-visitor' {
  declare module.exports: any;
}

declare module 'less/lib/less/index' {
  declare module.exports: any;
}

declare module 'less/lib/less/join-selector-visitor' {
  declare module.exports: any;
}

declare module 'less/lib/less/lessc_helper' {
  declare module.exports: any;
}

declare module 'less/lib/less/parser' {
  declare module.exports: any;
}

declare module 'less/lib/less/rhino' {
  declare module.exports: any;
}

declare module 'less/lib/less/source-map-output' {
  declare module.exports: any;
}

declare module 'less/lib/less/to-css-visitor' {
  declare module.exports: any;
}

declare module 'less/lib/less/tree' {
  declare module.exports: any;
}

declare module 'less/lib/less/tree/alpha' {
  declare module.exports: any;
}

declare module 'less/lib/less/tree/anonymous' {
  declare module.exports: any;
}

declare module 'less/lib/less/tree/assignment' {
  declare module.exports: any;
}

declare module 'less/lib/less/tree/call' {
  declare module.exports: any;
}

declare module 'less/lib/less/tree/color' {
  declare module.exports: any;
}

declare module 'less/lib/less/tree/comment' {
  declare module.exports: any;
}

declare module 'less/lib/less/tree/condition' {
  declare module.exports: any;
}

declare module 'less/lib/less/tree/detached-ruleset' {
  declare module.exports: any;
}

declare module 'less/lib/less/tree/dimension' {
  declare module.exports: any;
}

declare module 'less/lib/less/tree/directive' {
  declare module.exports: any;
}

declare module 'less/lib/less/tree/element' {
  declare module.exports: any;
}

declare module 'less/lib/less/tree/expression' {
  declare module.exports: any;
}

declare module 'less/lib/less/tree/extend' {
  declare module.exports: any;
}

declare module 'less/lib/less/tree/import' {
  declare module.exports: any;
}

declare module 'less/lib/less/tree/javascript' {
  declare module.exports: any;
}

declare module 'less/lib/less/tree/keyword' {
  declare module.exports: any;
}

declare module 'less/lib/less/tree/media' {
  declare module.exports: any;
}

declare module 'less/lib/less/tree/mixin' {
  declare module.exports: any;
}

declare module 'less/lib/less/tree/negative' {
  declare module.exports: any;
}

declare module 'less/lib/less/tree/operation' {
  declare module.exports: any;
}

declare module 'less/lib/less/tree/paren' {
  declare module.exports: any;
}

declare module 'less/lib/less/tree/quoted' {
  declare module.exports: any;
}

declare module 'less/lib/less/tree/rule' {
  declare module.exports: any;
}

declare module 'less/lib/less/tree/ruleset-call' {
  declare module.exports: any;
}

declare module 'less/lib/less/tree/ruleset' {
  declare module.exports: any;
}

declare module 'less/lib/less/tree/selector' {
  declare module.exports: any;
}

declare module 'less/lib/less/tree/unicode-descriptor' {
  declare module.exports: any;
}

declare module 'less/lib/less/tree/url' {
  declare module.exports: any;
}

declare module 'less/lib/less/tree/value' {
  declare module.exports: any;
}

declare module 'less/lib/less/tree/variable' {
  declare module.exports: any;
}

declare module 'less/lib/less/visitor' {
  declare module.exports: any;
}

declare module 'less/lib/source-map/source-map-0.1.31' {
  declare module.exports: any;
}

declare module 'less/lib/source-map/source-map-footer' {
  declare module.exports: any;
}

declare module 'less/lib/source-map/source-map-header' {
  declare module.exports: any;
}

declare module 'less/test/browser/common' {
  declare module.exports: any;
}

declare module 'less/test/browser/es5' {
  declare module.exports: any;
}

declare module 'less/test/browser/jasmine-html' {
  declare module.exports: any;
}

declare module 'less/test/browser/jasmine' {
  declare module.exports: any;
}

declare module 'less/test/browser/less' {
  declare module.exports: any;
}

declare module 'less/test/browser/phantom-runner' {
  declare module.exports: any;
}

declare module 'less/test/browser/runner-browser-options' {
  declare module.exports: any;
}

declare module 'less/test/browser/runner-browser-spec' {
  declare module.exports: any;
}

declare module 'less/test/browser/runner-console-errors' {
  declare module.exports: any;
}

declare module 'less/test/browser/runner-errors-options' {
  declare module.exports: any;
}

declare module 'less/test/browser/runner-errors-spec' {
  declare module.exports: any;
}

declare module 'less/test/browser/runner-global-vars-options' {
  declare module.exports: any;
}

declare module 'less/test/browser/runner-global-vars-spec' {
  declare module.exports: any;
}

declare module 'less/test/browser/runner-legacy-options' {
  declare module.exports: any;
}

declare module 'less/test/browser/runner-legacy-spec' {
  declare module.exports: any;
}

declare module 'less/test/browser/runner-main-options' {
  declare module.exports: any;
}

declare module 'less/test/browser/runner-main-spec' {
  declare module.exports: any;
}

declare module 'less/test/browser/runner-modify-vars-options' {
  declare module.exports: any;
}

declare module 'less/test/browser/runner-modify-vars-spec' {
  declare module.exports: any;
}

declare module 'less/test/browser/runner-no-js-errors-options' {
  declare module.exports: any;
}

declare module 'less/test/browser/runner-no-js-errors-spec' {
  declare module.exports: any;
}

declare module 'less/test/browser/runner-postProcessor-options' {
  declare module.exports: any;
}

declare module 'less/test/browser/runner-postProcessor' {
  declare module.exports: any;
}

declare module 'less/test/browser/runner-production-options' {
  declare module.exports: any;
}

declare module 'less/test/browser/runner-production-spec' {
  declare module.exports: any;
}

declare module 'less/test/browser/runner-relative-urls-options' {
  declare module.exports: any;
}

declare module 'less/test/browser/runner-relative-urls-spec' {
  declare module.exports: any;
}

declare module 'less/test/browser/runner-rootpath-options' {
  declare module.exports: any;
}

declare module 'less/test/browser/runner-rootpath-relative-options' {
  declare module.exports: any;
}

declare module 'less/test/browser/runner-rootpath-relative-spec' {
  declare module.exports: any;
}

declare module 'less/test/browser/runner-rootpath-spec' {
  declare module.exports: any;
}

declare module 'less/test/index' {
  declare module.exports: any;
}

declare module 'less/test/less-test' {
  declare module.exports: any;
}

declare module 'less/test/modify-vars' {
  declare module.exports: any;
}

declare module 'less/test/rhino/test-header' {
  declare module.exports: any;
}

declare module 'less/tmp/less' {
  declare module.exports: any;
}

// Filename aliases
declare module 'less/benchmark/less-benchmark.js' {
  declare module.exports: $Exports<'less/benchmark/less-benchmark'>;
}
declare module 'less/build/amd.js' {
  declare module.exports: $Exports<'less/build/amd'>;
}
declare module 'less/build/browser-header.js' {
  declare module.exports: $Exports<'less/build/browser-header'>;
}
declare module 'less/build/require-rhino.js' {
  declare module.exports: $Exports<'less/build/require-rhino'>;
}
declare module 'less/build/require.js' {
  declare module.exports: $Exports<'less/build/require'>;
}
declare module 'less/build/rhino-header.js' {
  declare module.exports: $Exports<'less/build/rhino-header'>;
}
declare module 'less/build/rhino-modules.js' {
  declare module.exports: $Exports<'less/build/rhino-modules'>;
}
declare module 'less/dist/less-1.1.0.js' {
  declare module.exports: $Exports<'less/dist/less-1.1.0'>;
}
declare module 'less/dist/less-1.1.0.min.js' {
  declare module.exports: $Exports<'less/dist/less-1.1.0.min'>;
}
declare module 'less/dist/less-1.1.1.js' {
  declare module.exports: $Exports<'less/dist/less-1.1.1'>;
}
declare module 'less/dist/less-1.1.1.min.js' {
  declare module.exports: $Exports<'less/dist/less-1.1.1.min'>;
}
declare module 'less/dist/less-1.1.2.js' {
  declare module.exports: $Exports<'less/dist/less-1.1.2'>;
}
declare module 'less/dist/less-1.1.2.min.js' {
  declare module.exports: $Exports<'less/dist/less-1.1.2.min'>;
}
declare module 'less/dist/less-1.1.3.js' {
  declare module.exports: $Exports<'less/dist/less-1.1.3'>;
}
declare module 'less/dist/less-1.1.3.min.js' {
  declare module.exports: $Exports<'less/dist/less-1.1.3.min'>;
}
declare module 'less/dist/less-1.1.4.js' {
  declare module.exports: $Exports<'less/dist/less-1.1.4'>;
}
declare module 'less/dist/less-1.1.4.min.js' {
  declare module.exports: $Exports<'less/dist/less-1.1.4.min'>;
}
declare module 'less/dist/less-1.1.5.js' {
  declare module.exports: $Exports<'less/dist/less-1.1.5'>;
}
declare module 'less/dist/less-1.1.5.min.js' {
  declare module.exports: $Exports<'less/dist/less-1.1.5.min'>;
}
declare module 'less/dist/less-1.1.6.js' {
  declare module.exports: $Exports<'less/dist/less-1.1.6'>;
}
declare module 'less/dist/less-1.1.6.min.js' {
  declare module.exports: $Exports<'less/dist/less-1.1.6.min'>;
}
declare module 'less/dist/less-1.2.0.js' {
  declare module.exports: $Exports<'less/dist/less-1.2.0'>;
}
declare module 'less/dist/less-1.2.0.min.js' {
  declare module.exports: $Exports<'less/dist/less-1.2.0.min'>;
}
declare module 'less/dist/less-1.2.1.js' {
  declare module.exports: $Exports<'less/dist/less-1.2.1'>;
}
declare module 'less/dist/less-1.2.1.min.js' {
  declare module.exports: $Exports<'less/dist/less-1.2.1.min'>;
}
declare module 'less/dist/less-1.2.2.js' {
  declare module.exports: $Exports<'less/dist/less-1.2.2'>;
}
declare module 'less/dist/less-1.2.2.min.js' {
  declare module.exports: $Exports<'less/dist/less-1.2.2.min'>;
}
declare module 'less/dist/less-1.3.0.js' {
  declare module.exports: $Exports<'less/dist/less-1.3.0'>;
}
declare module 'less/dist/less-1.3.0.min.js' {
  declare module.exports: $Exports<'less/dist/less-1.3.0.min'>;
}
declare module 'less/dist/less-1.3.1.js' {
  declare module.exports: $Exports<'less/dist/less-1.3.1'>;
}
declare module 'less/dist/less-1.3.1.min.js' {
  declare module.exports: $Exports<'less/dist/less-1.3.1.min'>;
}
declare module 'less/dist/less-1.3.2.js' {
  declare module.exports: $Exports<'less/dist/less-1.3.2'>;
}
declare module 'less/dist/less-1.3.2.min.js' {
  declare module.exports: $Exports<'less/dist/less-1.3.2.min'>;
}
declare module 'less/dist/less-1.3.3.js' {
  declare module.exports: $Exports<'less/dist/less-1.3.3'>;
}
declare module 'less/dist/less-1.3.3.min.js' {
  declare module.exports: $Exports<'less/dist/less-1.3.3.min'>;
}
declare module 'less/dist/less-1.4.0-beta.js' {
  declare module.exports: $Exports<'less/dist/less-1.4.0-beta'>;
}
declare module 'less/dist/less-1.4.0-beta.min.js' {
  declare module.exports: $Exports<'less/dist/less-1.4.0-beta.min'>;
}
declare module 'less/dist/less-1.4.0.js' {
  declare module.exports: $Exports<'less/dist/less-1.4.0'>;
}
declare module 'less/dist/less-1.4.0.min.js' {
  declare module.exports: $Exports<'less/dist/less-1.4.0.min'>;
}
declare module 'less/dist/less-1.4.1.js' {
  declare module.exports: $Exports<'less/dist/less-1.4.1'>;
}
declare module 'less/dist/less-1.4.1.min.js' {
  declare module.exports: $Exports<'less/dist/less-1.4.1.min'>;
}
declare module 'less/dist/less-1.4.2.js' {
  declare module.exports: $Exports<'less/dist/less-1.4.2'>;
}
declare module 'less/dist/less-1.4.2.min.js' {
  declare module.exports: $Exports<'less/dist/less-1.4.2.min'>;
}
declare module 'less/dist/less-1.5.0.js' {
  declare module.exports: $Exports<'less/dist/less-1.5.0'>;
}
declare module 'less/dist/less-1.5.0.min.js' {
  declare module.exports: $Exports<'less/dist/less-1.5.0.min'>;
}
declare module 'less/dist/less-1.5.1.js' {
  declare module.exports: $Exports<'less/dist/less-1.5.1'>;
}
declare module 'less/dist/less-1.5.1.min.js' {
  declare module.exports: $Exports<'less/dist/less-1.5.1.min'>;
}
declare module 'less/dist/less-1.6.0.js' {
  declare module.exports: $Exports<'less/dist/less-1.6.0'>;
}
declare module 'less/dist/less-1.6.0.min.js' {
  declare module.exports: $Exports<'less/dist/less-1.6.0.min'>;
}
declare module 'less/dist/less-1.6.1.js' {
  declare module.exports: $Exports<'less/dist/less-1.6.1'>;
}
declare module 'less/dist/less-1.6.1.min.js' {
  declare module.exports: $Exports<'less/dist/less-1.6.1.min'>;
}
declare module 'less/dist/less-1.6.2.js' {
  declare module.exports: $Exports<'less/dist/less-1.6.2'>;
}
declare module 'less/dist/less-1.6.2.min.js' {
  declare module.exports: $Exports<'less/dist/less-1.6.2.min'>;
}
declare module 'less/dist/less-1.6.3.js' {
  declare module.exports: $Exports<'less/dist/less-1.6.3'>;
}
declare module 'less/dist/less-1.6.3.min.js' {
  declare module.exports: $Exports<'less/dist/less-1.6.3.min'>;
}
declare module 'less/dist/less-1.7.0.js' {
  declare module.exports: $Exports<'less/dist/less-1.7.0'>;
}
declare module 'less/dist/less-1.7.0.min.js' {
  declare module.exports: $Exports<'less/dist/less-1.7.0.min'>;
}
declare module 'less/dist/less-1.7.1.js' {
  declare module.exports: $Exports<'less/dist/less-1.7.1'>;
}
declare module 'less/dist/less-1.7.1.min.js' {
  declare module.exports: $Exports<'less/dist/less-1.7.1.min'>;
}
declare module 'less/dist/less-1.7.2.js' {
  declare module.exports: $Exports<'less/dist/less-1.7.2'>;
}
declare module 'less/dist/less-1.7.2.min.js' {
  declare module.exports: $Exports<'less/dist/less-1.7.2.min'>;
}
declare module 'less/dist/less-1.7.3.js' {
  declare module.exports: $Exports<'less/dist/less-1.7.3'>;
}
declare module 'less/dist/less-1.7.3.min.js' {
  declare module.exports: $Exports<'less/dist/less-1.7.3.min'>;
}
declare module 'less/dist/less-1.7.4.js' {
  declare module.exports: $Exports<'less/dist/less-1.7.4'>;
}
declare module 'less/dist/less-1.7.4.min.js' {
  declare module.exports: $Exports<'less/dist/less-1.7.4.min'>;
}
declare module 'less/dist/less-1.7.5.js' {
  declare module.exports: $Exports<'less/dist/less-1.7.5'>;
}
declare module 'less/dist/less-1.7.5.min.js' {
  declare module.exports: $Exports<'less/dist/less-1.7.5.min'>;
}
declare module 'less/dist/less-rhino-1.1.3.js' {
  declare module.exports: $Exports<'less/dist/less-rhino-1.1.3'>;
}
declare module 'less/dist/less-rhino-1.1.5.js' {
  declare module.exports: $Exports<'less/dist/less-rhino-1.1.5'>;
}
declare module 'less/dist/less-rhino-1.3.1.js' {
  declare module.exports: $Exports<'less/dist/less-rhino-1.3.1'>;
}
declare module 'less/dist/less-rhino-1.3.2.js' {
  declare module.exports: $Exports<'less/dist/less-rhino-1.3.2'>;
}
declare module 'less/dist/less-rhino-1.3.3.js' {
  declare module.exports: $Exports<'less/dist/less-rhino-1.3.3'>;
}
declare module 'less/dist/less-rhino-1.4.0.js' {
  declare module.exports: $Exports<'less/dist/less-rhino-1.4.0'>;
}
declare module 'less/dist/less-rhino-1.5.1.js' {
  declare module.exports: $Exports<'less/dist/less-rhino-1.5.1'>;
}
declare module 'less/dist/less-rhino-1.6.2.js' {
  declare module.exports: $Exports<'less/dist/less-rhino-1.6.2'>;
}
declare module 'less/dist/less-rhino-1.6.3.js' {
  declare module.exports: $Exports<'less/dist/less-rhino-1.6.3'>;
}
declare module 'less/dist/less-rhino-1.7.0.js' {
  declare module.exports: $Exports<'less/dist/less-rhino-1.7.0'>;
}
declare module 'less/dist/less-rhino-1.7.1.js' {
  declare module.exports: $Exports<'less/dist/less-rhino-1.7.1'>;
}
declare module 'less/dist/less-rhino-1.7.2.js' {
  declare module.exports: $Exports<'less/dist/less-rhino-1.7.2'>;
}
declare module 'less/dist/less-rhino-1.7.3.js' {
  declare module.exports: $Exports<'less/dist/less-rhino-1.7.3'>;
}
declare module 'less/dist/less-rhino-1.7.4.js' {
  declare module.exports: $Exports<'less/dist/less-rhino-1.7.4'>;
}
declare module 'less/dist/less-rhino-1.7.5.js' {
  declare module.exports: $Exports<'less/dist/less-rhino-1.7.5'>;
}
declare module 'less/dist/lessc-rhino-1.6.2.js' {
  declare module.exports: $Exports<'less/dist/lessc-rhino-1.6.2'>;
}
declare module 'less/dist/lessc-rhino-1.6.3.js' {
  declare module.exports: $Exports<'less/dist/lessc-rhino-1.6.3'>;
}
declare module 'less/dist/lessc-rhino-1.7.0.js' {
  declare module.exports: $Exports<'less/dist/lessc-rhino-1.7.0'>;
}
declare module 'less/dist/lessc-rhino-1.7.1.js' {
  declare module.exports: $Exports<'less/dist/lessc-rhino-1.7.1'>;
}
declare module 'less/dist/lessc-rhino-1.7.2.js' {
  declare module.exports: $Exports<'less/dist/lessc-rhino-1.7.2'>;
}
declare module 'less/dist/lessc-rhino-1.7.3.js' {
  declare module.exports: $Exports<'less/dist/lessc-rhino-1.7.3'>;
}
declare module 'less/dist/lessc-rhino-1.7.4.js' {
  declare module.exports: $Exports<'less/dist/lessc-rhino-1.7.4'>;
}
declare module 'less/dist/lessc-rhino-1.7.5.js' {
  declare module.exports: $Exports<'less/dist/lessc-rhino-1.7.5'>;
}
declare module 'less/Gruntfile.js' {
  declare module.exports: $Exports<'less/Gruntfile'>;
}
declare module 'less/lib/less/browser.js' {
  declare module.exports: $Exports<'less/lib/less/browser'>;
}
declare module 'less/lib/less/colors.js' {
  declare module.exports: $Exports<'less/lib/less/colors'>;
}
declare module 'less/lib/less/encoder.js' {
  declare module.exports: $Exports<'less/lib/less/encoder'>;
}
declare module 'less/lib/less/env.js' {
  declare module.exports: $Exports<'less/lib/less/env'>;
}
declare module 'less/lib/less/extend-visitor.js' {
  declare module.exports: $Exports<'less/lib/less/extend-visitor'>;
}
declare module 'less/lib/less/fs.js' {
  declare module.exports: $Exports<'less/lib/less/fs'>;
}
declare module 'less/lib/less/functions.js' {
  declare module.exports: $Exports<'less/lib/less/functions'>;
}
declare module 'less/lib/less/import-visitor.js' {
  declare module.exports: $Exports<'less/lib/less/import-visitor'>;
}
declare module 'less/lib/less/index.js' {
  declare module.exports: $Exports<'less/lib/less/index'>;
}
declare module 'less/lib/less/join-selector-visitor.js' {
  declare module.exports: $Exports<'less/lib/less/join-selector-visitor'>;
}
declare module 'less/lib/less/lessc_helper.js' {
  declare module.exports: $Exports<'less/lib/less/lessc_helper'>;
}
declare module 'less/lib/less/parser.js' {
  declare module.exports: $Exports<'less/lib/less/parser'>;
}
declare module 'less/lib/less/rhino.js' {
  declare module.exports: $Exports<'less/lib/less/rhino'>;
}
declare module 'less/lib/less/source-map-output.js' {
  declare module.exports: $Exports<'less/lib/less/source-map-output'>;
}
declare module 'less/lib/less/to-css-visitor.js' {
  declare module.exports: $Exports<'less/lib/less/to-css-visitor'>;
}
declare module 'less/lib/less/tree.js' {
  declare module.exports: $Exports<'less/lib/less/tree'>;
}
declare module 'less/lib/less/tree/alpha.js' {
  declare module.exports: $Exports<'less/lib/less/tree/alpha'>;
}
declare module 'less/lib/less/tree/anonymous.js' {
  declare module.exports: $Exports<'less/lib/less/tree/anonymous'>;
}
declare module 'less/lib/less/tree/assignment.js' {
  declare module.exports: $Exports<'less/lib/less/tree/assignment'>;
}
declare module 'less/lib/less/tree/call.js' {
  declare module.exports: $Exports<'less/lib/less/tree/call'>;
}
declare module 'less/lib/less/tree/color.js' {
  declare module.exports: $Exports<'less/lib/less/tree/color'>;
}
declare module 'less/lib/less/tree/comment.js' {
  declare module.exports: $Exports<'less/lib/less/tree/comment'>;
}
declare module 'less/lib/less/tree/condition.js' {
  declare module.exports: $Exports<'less/lib/less/tree/condition'>;
}
declare module 'less/lib/less/tree/detached-ruleset.js' {
  declare module.exports: $Exports<'less/lib/less/tree/detached-ruleset'>;
}
declare module 'less/lib/less/tree/dimension.js' {
  declare module.exports: $Exports<'less/lib/less/tree/dimension'>;
}
declare module 'less/lib/less/tree/directive.js' {
  declare module.exports: $Exports<'less/lib/less/tree/directive'>;
}
declare module 'less/lib/less/tree/element.js' {
  declare module.exports: $Exports<'less/lib/less/tree/element'>;
}
declare module 'less/lib/less/tree/expression.js' {
  declare module.exports: $Exports<'less/lib/less/tree/expression'>;
}
declare module 'less/lib/less/tree/extend.js' {
  declare module.exports: $Exports<'less/lib/less/tree/extend'>;
}
declare module 'less/lib/less/tree/import.js' {
  declare module.exports: $Exports<'less/lib/less/tree/import'>;
}
declare module 'less/lib/less/tree/javascript.js' {
  declare module.exports: $Exports<'less/lib/less/tree/javascript'>;
}
declare module 'less/lib/less/tree/keyword.js' {
  declare module.exports: $Exports<'less/lib/less/tree/keyword'>;
}
declare module 'less/lib/less/tree/media.js' {
  declare module.exports: $Exports<'less/lib/less/tree/media'>;
}
declare module 'less/lib/less/tree/mixin.js' {
  declare module.exports: $Exports<'less/lib/less/tree/mixin'>;
}
declare module 'less/lib/less/tree/negative.js' {
  declare module.exports: $Exports<'less/lib/less/tree/negative'>;
}
declare module 'less/lib/less/tree/operation.js' {
  declare module.exports: $Exports<'less/lib/less/tree/operation'>;
}
declare module 'less/lib/less/tree/paren.js' {
  declare module.exports: $Exports<'less/lib/less/tree/paren'>;
}
declare module 'less/lib/less/tree/quoted.js' {
  declare module.exports: $Exports<'less/lib/less/tree/quoted'>;
}
declare module 'less/lib/less/tree/rule.js' {
  declare module.exports: $Exports<'less/lib/less/tree/rule'>;
}
declare module 'less/lib/less/tree/ruleset-call.js' {
  declare module.exports: $Exports<'less/lib/less/tree/ruleset-call'>;
}
declare module 'less/lib/less/tree/ruleset.js' {
  declare module.exports: $Exports<'less/lib/less/tree/ruleset'>;
}
declare module 'less/lib/less/tree/selector.js' {
  declare module.exports: $Exports<'less/lib/less/tree/selector'>;
}
declare module 'less/lib/less/tree/unicode-descriptor.js' {
  declare module.exports: $Exports<'less/lib/less/tree/unicode-descriptor'>;
}
declare module 'less/lib/less/tree/url.js' {
  declare module.exports: $Exports<'less/lib/less/tree/url'>;
}
declare module 'less/lib/less/tree/value.js' {
  declare module.exports: $Exports<'less/lib/less/tree/value'>;
}
declare module 'less/lib/less/tree/variable.js' {
  declare module.exports: $Exports<'less/lib/less/tree/variable'>;
}
declare module 'less/lib/less/visitor.js' {
  declare module.exports: $Exports<'less/lib/less/visitor'>;
}
declare module 'less/lib/source-map/source-map-0.1.31.js' {
  declare module.exports: $Exports<'less/lib/source-map/source-map-0.1.31'>;
}
declare module 'less/lib/source-map/source-map-footer.js' {
  declare module.exports: $Exports<'less/lib/source-map/source-map-footer'>;
}
declare module 'less/lib/source-map/source-map-header.js' {
  declare module.exports: $Exports<'less/lib/source-map/source-map-header'>;
}
declare module 'less/test/browser/common.js' {
  declare module.exports: $Exports<'less/test/browser/common'>;
}
declare module 'less/test/browser/es5.js' {
  declare module.exports: $Exports<'less/test/browser/es5'>;
}
declare module 'less/test/browser/jasmine-html.js' {
  declare module.exports: $Exports<'less/test/browser/jasmine-html'>;
}
declare module 'less/test/browser/jasmine.js' {
  declare module.exports: $Exports<'less/test/browser/jasmine'>;
}
declare module 'less/test/browser/less.js' {
  declare module.exports: $Exports<'less/test/browser/less'>;
}
declare module 'less/test/browser/phantom-runner.js' {
  declare module.exports: $Exports<'less/test/browser/phantom-runner'>;
}
declare module 'less/test/browser/runner-browser-options.js' {
  declare module.exports: $Exports<'less/test/browser/runner-browser-options'>;
}
declare module 'less/test/browser/runner-browser-spec.js' {
  declare module.exports: $Exports<'less/test/browser/runner-browser-spec'>;
}
declare module 'less/test/browser/runner-console-errors.js' {
  declare module.exports: $Exports<'less/test/browser/runner-console-errors'>;
}
declare module 'less/test/browser/runner-errors-options.js' {
  declare module.exports: $Exports<'less/test/browser/runner-errors-options'>;
}
declare module 'less/test/browser/runner-errors-spec.js' {
  declare module.exports: $Exports<'less/test/browser/runner-errors-spec'>;
}
declare module 'less/test/browser/runner-global-vars-options.js' {
  declare module.exports: $Exports<'less/test/browser/runner-global-vars-options'>;
}
declare module 'less/test/browser/runner-global-vars-spec.js' {
  declare module.exports: $Exports<'less/test/browser/runner-global-vars-spec'>;
}
declare module 'less/test/browser/runner-legacy-options.js' {
  declare module.exports: $Exports<'less/test/browser/runner-legacy-options'>;
}
declare module 'less/test/browser/runner-legacy-spec.js' {
  declare module.exports: $Exports<'less/test/browser/runner-legacy-spec'>;
}
declare module 'less/test/browser/runner-main-options.js' {
  declare module.exports: $Exports<'less/test/browser/runner-main-options'>;
}
declare module 'less/test/browser/runner-main-spec.js' {
  declare module.exports: $Exports<'less/test/browser/runner-main-spec'>;
}
declare module 'less/test/browser/runner-modify-vars-options.js' {
  declare module.exports: $Exports<'less/test/browser/runner-modify-vars-options'>;
}
declare module 'less/test/browser/runner-modify-vars-spec.js' {
  declare module.exports: $Exports<'less/test/browser/runner-modify-vars-spec'>;
}
declare module 'less/test/browser/runner-no-js-errors-options.js' {
  declare module.exports: $Exports<'less/test/browser/runner-no-js-errors-options'>;
}
declare module 'less/test/browser/runner-no-js-errors-spec.js' {
  declare module.exports: $Exports<'less/test/browser/runner-no-js-errors-spec'>;
}
declare module 'less/test/browser/runner-postProcessor-options.js' {
  declare module.exports: $Exports<'less/test/browser/runner-postProcessor-options'>;
}
declare module 'less/test/browser/runner-postProcessor.js' {
  declare module.exports: $Exports<'less/test/browser/runner-postProcessor'>;
}
declare module 'less/test/browser/runner-production-options.js' {
  declare module.exports: $Exports<'less/test/browser/runner-production-options'>;
}
declare module 'less/test/browser/runner-production-spec.js' {
  declare module.exports: $Exports<'less/test/browser/runner-production-spec'>;
}
declare module 'less/test/browser/runner-relative-urls-options.js' {
  declare module.exports: $Exports<'less/test/browser/runner-relative-urls-options'>;
}
declare module 'less/test/browser/runner-relative-urls-spec.js' {
  declare module.exports: $Exports<'less/test/browser/runner-relative-urls-spec'>;
}
declare module 'less/test/browser/runner-rootpath-options.js' {
  declare module.exports: $Exports<'less/test/browser/runner-rootpath-options'>;
}
declare module 'less/test/browser/runner-rootpath-relative-options.js' {
  declare module.exports: $Exports<'less/test/browser/runner-rootpath-relative-options'>;
}
declare module 'less/test/browser/runner-rootpath-relative-spec.js' {
  declare module.exports: $Exports<'less/test/browser/runner-rootpath-relative-spec'>;
}
declare module 'less/test/browser/runner-rootpath-spec.js' {
  declare module.exports: $Exports<'less/test/browser/runner-rootpath-spec'>;
}
declare module 'less/test/index.js' {
  declare module.exports: $Exports<'less/test/index'>;
}
declare module 'less/test/less-test.js' {
  declare module.exports: $Exports<'less/test/less-test'>;
}
declare module 'less/test/modify-vars.js' {
  declare module.exports: $Exports<'less/test/modify-vars'>;
}
declare module 'less/test/rhino/test-header.js' {
  declare module.exports: $Exports<'less/test/rhino/test-header'>;
}
declare module 'less/tmp/less.js' {
  declare module.exports: $Exports<'less/tmp/less'>;
}
