// flow-typed signature: 417e5453d28d2c851ef2f2df3c6bfb44
// flow-typed version: <<STUB>>/nodeunit_v0.9.x/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nodeunit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nodeunit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nodeunit/deps/async' {
  declare module.exports: any;
}

declare module 'nodeunit/deps/console.log' {
  declare module.exports: any;
}

declare module 'nodeunit/deps/ejs/benchmark' {
  declare module.exports: any;
}

declare module 'nodeunit/deps/ejs/ejs' {
  declare module.exports: any;
}

declare module 'nodeunit/deps/ejs/ejs.min' {
  declare module.exports: any;
}

declare module 'nodeunit/deps/ejs/examples/list' {
  declare module.exports: any;
}

declare module 'nodeunit/deps/ejs/index' {
  declare module.exports: any;
}

declare module 'nodeunit/deps/ejs/lib/ejs' {
  declare module.exports: any;
}

declare module 'nodeunit/deps/ejs/lib/filters' {
  declare module.exports: any;
}

declare module 'nodeunit/deps/ejs/lib/utils' {
  declare module.exports: any;
}

declare module 'nodeunit/deps/ejs/support/compile' {
  declare module.exports: any;
}

declare module 'nodeunit/deps/ejs/test/ejs.test' {
  declare module.exports: any;
}

declare module 'nodeunit/deps/json2' {
  declare module.exports: any;
}

declare module 'nodeunit/examples/browser/nodeunit' {
  declare module.exports: any;
}

declare module 'nodeunit/examples/browser/suite1' {
  declare module.exports: any;
}

declare module 'nodeunit/examples/browser/suite2' {
  declare module.exports: any;
}

declare module 'nodeunit/examples/browser/suite3' {
  declare module.exports: any;
}

declare module 'nodeunit/examples/nested/nested_reporter_test.unit' {
  declare module.exports: any;
}

declare module 'nodeunit/lib/assert' {
  declare module.exports: any;
}

declare module 'nodeunit/lib/core' {
  declare module.exports: any;
}

declare module 'nodeunit/lib/nodeunit' {
  declare module.exports: any;
}

declare module 'nodeunit/lib/reporters/browser' {
  declare module.exports: any;
}

declare module 'nodeunit/lib/reporters/default' {
  declare module.exports: any;
}

declare module 'nodeunit/lib/reporters/eclipse' {
  declare module.exports: any;
}

declare module 'nodeunit/lib/reporters/html' {
  declare module.exports: any;
}

declare module 'nodeunit/lib/reporters/index' {
  declare module.exports: any;
}

declare module 'nodeunit/lib/reporters/junit' {
  declare module.exports: any;
}

declare module 'nodeunit/lib/reporters/lcov' {
  declare module.exports: any;
}

declare module 'nodeunit/lib/reporters/machineout' {
  declare module.exports: any;
}

declare module 'nodeunit/lib/reporters/minimal' {
  declare module.exports: any;
}

declare module 'nodeunit/lib/reporters/nested' {
  declare module.exports: any;
}

declare module 'nodeunit/lib/reporters/skip_passed' {
  declare module.exports: any;
}

declare module 'nodeunit/lib/reporters/tap' {
  declare module.exports: any;
}

declare module 'nodeunit/lib/reporters/verbose' {
  declare module.exports: any;
}

declare module 'nodeunit/lib/track' {
  declare module.exports: any;
}

declare module 'nodeunit/lib/types' {
  declare module.exports: any;
}

declare module 'nodeunit/lib/utils' {
  declare module.exports: any;
}

declare module 'nodeunit/share/license' {
  declare module.exports: any;
}

declare module 'nodeunit/test/fixtures/dir/example_test_sub' {
  declare module.exports: any;
}

declare module 'nodeunit/test/fixtures/dir/mock_module3' {
  declare module.exports: any;
}

declare module 'nodeunit/test/fixtures/dir/mock_module4' {
  declare module.exports: any;
}

declare module 'nodeunit/test/fixtures/example_test' {
  declare module.exports: any;
}

declare module 'nodeunit/test/fixtures/mock_module1' {
  declare module.exports: any;
}

declare module 'nodeunit/test/fixtures/mock_module2' {
  declare module.exports: any;
}

declare module 'nodeunit/test/fixtures/raw_jscode1' {
  declare module.exports: any;
}

declare module 'nodeunit/test/fixtures/raw_jscode2' {
  declare module.exports: any;
}

declare module 'nodeunit/test/fixtures/raw_jscode3' {
  declare module.exports: any;
}

declare module 'nodeunit/test/test-base' {
  declare module.exports: any;
}

declare module 'nodeunit/test/test-bettererrors' {
  declare module.exports: any;
}

declare module 'nodeunit/test/test-cli' {
  declare module.exports: any;
}

declare module 'nodeunit/test/test-failing-callbacks' {
  declare module.exports: any;
}

declare module 'nodeunit/test/test-httputil' {
  declare module.exports: any;
}

declare module 'nodeunit/test/test-runfiles' {
  declare module.exports: any;
}

declare module 'nodeunit/test/test-runmodule' {
  declare module.exports: any;
}

declare module 'nodeunit/test/test-runtest' {
  declare module.exports: any;
}

declare module 'nodeunit/test/test-sandbox' {
  declare module.exports: any;
}

declare module 'nodeunit/test/test-testcase-legacy' {
  declare module.exports: any;
}

declare module 'nodeunit/test/test-testcase' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nodeunit/deps/async.js' {
  declare module.exports: $Exports<'nodeunit/deps/async'>;
}
declare module 'nodeunit/deps/console.log.js' {
  declare module.exports: $Exports<'nodeunit/deps/console.log'>;
}
declare module 'nodeunit/deps/ejs/benchmark.js' {
  declare module.exports: $Exports<'nodeunit/deps/ejs/benchmark'>;
}
declare module 'nodeunit/deps/ejs/ejs.js' {
  declare module.exports: $Exports<'nodeunit/deps/ejs/ejs'>;
}
declare module 'nodeunit/deps/ejs/ejs.min.js' {
  declare module.exports: $Exports<'nodeunit/deps/ejs/ejs.min'>;
}
declare module 'nodeunit/deps/ejs/examples/list.js' {
  declare module.exports: $Exports<'nodeunit/deps/ejs/examples/list'>;
}
declare module 'nodeunit/deps/ejs/index.js' {
  declare module.exports: $Exports<'nodeunit/deps/ejs/index'>;
}
declare module 'nodeunit/deps/ejs/lib/ejs.js' {
  declare module.exports: $Exports<'nodeunit/deps/ejs/lib/ejs'>;
}
declare module 'nodeunit/deps/ejs/lib/filters.js' {
  declare module.exports: $Exports<'nodeunit/deps/ejs/lib/filters'>;
}
declare module 'nodeunit/deps/ejs/lib/utils.js' {
  declare module.exports: $Exports<'nodeunit/deps/ejs/lib/utils'>;
}
declare module 'nodeunit/deps/ejs/support/compile.js' {
  declare module.exports: $Exports<'nodeunit/deps/ejs/support/compile'>;
}
declare module 'nodeunit/deps/ejs/test/ejs.test.js' {
  declare module.exports: $Exports<'nodeunit/deps/ejs/test/ejs.test'>;
}
declare module 'nodeunit/deps/json2.js' {
  declare module.exports: $Exports<'nodeunit/deps/json2'>;
}
declare module 'nodeunit/examples/browser/nodeunit.js' {
  declare module.exports: $Exports<'nodeunit/examples/browser/nodeunit'>;
}
declare module 'nodeunit/examples/browser/suite1.js' {
  declare module.exports: $Exports<'nodeunit/examples/browser/suite1'>;
}
declare module 'nodeunit/examples/browser/suite2.js' {
  declare module.exports: $Exports<'nodeunit/examples/browser/suite2'>;
}
declare module 'nodeunit/examples/browser/suite3.js' {
  declare module.exports: $Exports<'nodeunit/examples/browser/suite3'>;
}
declare module 'nodeunit/examples/nested/nested_reporter_test.unit.js' {
  declare module.exports: $Exports<'nodeunit/examples/nested/nested_reporter_test.unit'>;
}
declare module 'nodeunit/index' {
  declare module.exports: $Exports<'nodeunit'>;
}
declare module 'nodeunit/index.js' {
  declare module.exports: $Exports<'nodeunit'>;
}
declare module 'nodeunit/lib/assert.js' {
  declare module.exports: $Exports<'nodeunit/lib/assert'>;
}
declare module 'nodeunit/lib/core.js' {
  declare module.exports: $Exports<'nodeunit/lib/core'>;
}
declare module 'nodeunit/lib/nodeunit.js' {
  declare module.exports: $Exports<'nodeunit/lib/nodeunit'>;
}
declare module 'nodeunit/lib/reporters/browser.js' {
  declare module.exports: $Exports<'nodeunit/lib/reporters/browser'>;
}
declare module 'nodeunit/lib/reporters/default.js' {
  declare module.exports: $Exports<'nodeunit/lib/reporters/default'>;
}
declare module 'nodeunit/lib/reporters/eclipse.js' {
  declare module.exports: $Exports<'nodeunit/lib/reporters/eclipse'>;
}
declare module 'nodeunit/lib/reporters/html.js' {
  declare module.exports: $Exports<'nodeunit/lib/reporters/html'>;
}
declare module 'nodeunit/lib/reporters/index.js' {
  declare module.exports: $Exports<'nodeunit/lib/reporters/index'>;
}
declare module 'nodeunit/lib/reporters/junit.js' {
  declare module.exports: $Exports<'nodeunit/lib/reporters/junit'>;
}
declare module 'nodeunit/lib/reporters/lcov.js' {
  declare module.exports: $Exports<'nodeunit/lib/reporters/lcov'>;
}
declare module 'nodeunit/lib/reporters/machineout.js' {
  declare module.exports: $Exports<'nodeunit/lib/reporters/machineout'>;
}
declare module 'nodeunit/lib/reporters/minimal.js' {
  declare module.exports: $Exports<'nodeunit/lib/reporters/minimal'>;
}
declare module 'nodeunit/lib/reporters/nested.js' {
  declare module.exports: $Exports<'nodeunit/lib/reporters/nested'>;
}
declare module 'nodeunit/lib/reporters/skip_passed.js' {
  declare module.exports: $Exports<'nodeunit/lib/reporters/skip_passed'>;
}
declare module 'nodeunit/lib/reporters/tap.js' {
  declare module.exports: $Exports<'nodeunit/lib/reporters/tap'>;
}
declare module 'nodeunit/lib/reporters/verbose.js' {
  declare module.exports: $Exports<'nodeunit/lib/reporters/verbose'>;
}
declare module 'nodeunit/lib/track.js' {
  declare module.exports: $Exports<'nodeunit/lib/track'>;
}
declare module 'nodeunit/lib/types.js' {
  declare module.exports: $Exports<'nodeunit/lib/types'>;
}
declare module 'nodeunit/lib/utils.js' {
  declare module.exports: $Exports<'nodeunit/lib/utils'>;
}
declare module 'nodeunit/share/license.js' {
  declare module.exports: $Exports<'nodeunit/share/license'>;
}
declare module 'nodeunit/test/fixtures/dir/example_test_sub.js' {
  declare module.exports: $Exports<'nodeunit/test/fixtures/dir/example_test_sub'>;
}
declare module 'nodeunit/test/fixtures/dir/mock_module3.js' {
  declare module.exports: $Exports<'nodeunit/test/fixtures/dir/mock_module3'>;
}
declare module 'nodeunit/test/fixtures/dir/mock_module4.js' {
  declare module.exports: $Exports<'nodeunit/test/fixtures/dir/mock_module4'>;
}
declare module 'nodeunit/test/fixtures/example_test.js' {
  declare module.exports: $Exports<'nodeunit/test/fixtures/example_test'>;
}
declare module 'nodeunit/test/fixtures/mock_module1.js' {
  declare module.exports: $Exports<'nodeunit/test/fixtures/mock_module1'>;
}
declare module 'nodeunit/test/fixtures/mock_module2.js' {
  declare module.exports: $Exports<'nodeunit/test/fixtures/mock_module2'>;
}
declare module 'nodeunit/test/fixtures/raw_jscode1.js' {
  declare module.exports: $Exports<'nodeunit/test/fixtures/raw_jscode1'>;
}
declare module 'nodeunit/test/fixtures/raw_jscode2.js' {
  declare module.exports: $Exports<'nodeunit/test/fixtures/raw_jscode2'>;
}
declare module 'nodeunit/test/fixtures/raw_jscode3.js' {
  declare module.exports: $Exports<'nodeunit/test/fixtures/raw_jscode3'>;
}
declare module 'nodeunit/test/test-base.js' {
  declare module.exports: $Exports<'nodeunit/test/test-base'>;
}
declare module 'nodeunit/test/test-bettererrors.js' {
  declare module.exports: $Exports<'nodeunit/test/test-bettererrors'>;
}
declare module 'nodeunit/test/test-cli.js' {
  declare module.exports: $Exports<'nodeunit/test/test-cli'>;
}
declare module 'nodeunit/test/test-failing-callbacks.js' {
  declare module.exports: $Exports<'nodeunit/test/test-failing-callbacks'>;
}
declare module 'nodeunit/test/test-httputil.js' {
  declare module.exports: $Exports<'nodeunit/test/test-httputil'>;
}
declare module 'nodeunit/test/test-runfiles.js' {
  declare module.exports: $Exports<'nodeunit/test/test-runfiles'>;
}
declare module 'nodeunit/test/test-runmodule.js' {
  declare module.exports: $Exports<'nodeunit/test/test-runmodule'>;
}
declare module 'nodeunit/test/test-runtest.js' {
  declare module.exports: $Exports<'nodeunit/test/test-runtest'>;
}
declare module 'nodeunit/test/test-sandbox.js' {
  declare module.exports: $Exports<'nodeunit/test/test-sandbox'>;
}
declare module 'nodeunit/test/test-testcase-legacy.js' {
  declare module.exports: $Exports<'nodeunit/test/test-testcase-legacy'>;
}
declare module 'nodeunit/test/test-testcase.js' {
  declare module.exports: $Exports<'nodeunit/test/test-testcase'>;
}
