// flow-typed signature: a59a5deecdeee9a353b420aeb76638e4
// flow-typed version: <<STUB>>/request_v2.47.x/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'request'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'request' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'request/lib/cookies' {
  declare module.exports: any;
}

declare module 'request/lib/copy' {
  declare module.exports: any;
}

declare module 'request/lib/debug' {
  declare module.exports: any;
}

declare module 'request/lib/helpers' {
  declare module.exports: any;
}

declare module 'request/request' {
  declare module.exports: any;
}

// Filename aliases
declare module 'request/index' {
  declare module.exports: $Exports<'request'>;
}
declare module 'request/index.js' {
  declare module.exports: $Exports<'request'>;
}
declare module 'request/lib/cookies.js' {
  declare module.exports: $Exports<'request/lib/cookies'>;
}
declare module 'request/lib/copy.js' {
  declare module.exports: $Exports<'request/lib/copy'>;
}
declare module 'request/lib/debug.js' {
  declare module.exports: $Exports<'request/lib/debug'>;
}
declare module 'request/lib/helpers.js' {
  declare module.exports: $Exports<'request/lib/helpers'>;
}
declare module 'request/request.js' {
  declare module.exports: $Exports<'request/request'>;
}
