// flow-typed signature: f55652efbbaac1126e8ff998071132c3
// flow-typed version: <<STUB>>/shelljs_v0.5.x/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'shelljs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'shelljs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'shelljs/global' {
  declare module.exports: any;
}

declare module 'shelljs/make' {
  declare module.exports: any;
}

declare module 'shelljs/scripts/generate-docs' {
  declare module.exports: any;
}

declare module 'shelljs/scripts/run-tests' {
  declare module.exports: any;
}

declare module 'shelljs/shell' {
  declare module.exports: any;
}

declare module 'shelljs/src/cat' {
  declare module.exports: any;
}

declare module 'shelljs/src/cd' {
  declare module.exports: any;
}

declare module 'shelljs/src/chmod' {
  declare module.exports: any;
}

declare module 'shelljs/src/common' {
  declare module.exports: any;
}

declare module 'shelljs/src/cp' {
  declare module.exports: any;
}

declare module 'shelljs/src/dirs' {
  declare module.exports: any;
}

declare module 'shelljs/src/echo' {
  declare module.exports: any;
}

declare module 'shelljs/src/error' {
  declare module.exports: any;
}

declare module 'shelljs/src/exec' {
  declare module.exports: any;
}

declare module 'shelljs/src/find' {
  declare module.exports: any;
}

declare module 'shelljs/src/grep' {
  declare module.exports: any;
}

declare module 'shelljs/src/ln' {
  declare module.exports: any;
}

declare module 'shelljs/src/ls' {
  declare module.exports: any;
}

declare module 'shelljs/src/mkdir' {
  declare module.exports: any;
}

declare module 'shelljs/src/mv' {
  declare module.exports: any;
}

declare module 'shelljs/src/popd' {
  declare module.exports: any;
}

declare module 'shelljs/src/pushd' {
  declare module.exports: any;
}

declare module 'shelljs/src/pwd' {
  declare module.exports: any;
}

declare module 'shelljs/src/rm' {
  declare module.exports: any;
}

declare module 'shelljs/src/sed' {
  declare module.exports: any;
}

declare module 'shelljs/src/tempdir' {
  declare module.exports: any;
}

declare module 'shelljs/src/test' {
  declare module.exports: any;
}

declare module 'shelljs/src/to' {
  declare module.exports: any;
}

declare module 'shelljs/src/toEnd' {
  declare module.exports: any;
}

declare module 'shelljs/src/which' {
  declare module.exports: any;
}

// Filename aliases
declare module 'shelljs/global.js' {
  declare module.exports: $Exports<'shelljs/global'>;
}
declare module 'shelljs/make.js' {
  declare module.exports: $Exports<'shelljs/make'>;
}
declare module 'shelljs/scripts/generate-docs.js' {
  declare module.exports: $Exports<'shelljs/scripts/generate-docs'>;
}
declare module 'shelljs/scripts/run-tests.js' {
  declare module.exports: $Exports<'shelljs/scripts/run-tests'>;
}
declare module 'shelljs/shell.js' {
  declare module.exports: $Exports<'shelljs/shell'>;
}
declare module 'shelljs/src/cat.js' {
  declare module.exports: $Exports<'shelljs/src/cat'>;
}
declare module 'shelljs/src/cd.js' {
  declare module.exports: $Exports<'shelljs/src/cd'>;
}
declare module 'shelljs/src/chmod.js' {
  declare module.exports: $Exports<'shelljs/src/chmod'>;
}
declare module 'shelljs/src/common.js' {
  declare module.exports: $Exports<'shelljs/src/common'>;
}
declare module 'shelljs/src/cp.js' {
  declare module.exports: $Exports<'shelljs/src/cp'>;
}
declare module 'shelljs/src/dirs.js' {
  declare module.exports: $Exports<'shelljs/src/dirs'>;
}
declare module 'shelljs/src/echo.js' {
  declare module.exports: $Exports<'shelljs/src/echo'>;
}
declare module 'shelljs/src/error.js' {
  declare module.exports: $Exports<'shelljs/src/error'>;
}
declare module 'shelljs/src/exec.js' {
  declare module.exports: $Exports<'shelljs/src/exec'>;
}
declare module 'shelljs/src/find.js' {
  declare module.exports: $Exports<'shelljs/src/find'>;
}
declare module 'shelljs/src/grep.js' {
  declare module.exports: $Exports<'shelljs/src/grep'>;
}
declare module 'shelljs/src/ln.js' {
  declare module.exports: $Exports<'shelljs/src/ln'>;
}
declare module 'shelljs/src/ls.js' {
  declare module.exports: $Exports<'shelljs/src/ls'>;
}
declare module 'shelljs/src/mkdir.js' {
  declare module.exports: $Exports<'shelljs/src/mkdir'>;
}
declare module 'shelljs/src/mv.js' {
  declare module.exports: $Exports<'shelljs/src/mv'>;
}
declare module 'shelljs/src/popd.js' {
  declare module.exports: $Exports<'shelljs/src/popd'>;
}
declare module 'shelljs/src/pushd.js' {
  declare module.exports: $Exports<'shelljs/src/pushd'>;
}
declare module 'shelljs/src/pwd.js' {
  declare module.exports: $Exports<'shelljs/src/pwd'>;
}
declare module 'shelljs/src/rm.js' {
  declare module.exports: $Exports<'shelljs/src/rm'>;
}
declare module 'shelljs/src/sed.js' {
  declare module.exports: $Exports<'shelljs/src/sed'>;
}
declare module 'shelljs/src/tempdir.js' {
  declare module.exports: $Exports<'shelljs/src/tempdir'>;
}
declare module 'shelljs/src/test.js' {
  declare module.exports: $Exports<'shelljs/src/test'>;
}
declare module 'shelljs/src/to.js' {
  declare module.exports: $Exports<'shelljs/src/to'>;
}
declare module 'shelljs/src/toEnd.js' {
  declare module.exports: $Exports<'shelljs/src/toEnd'>;
}
declare module 'shelljs/src/which.js' {
  declare module.exports: $Exports<'shelljs/src/which'>;
}
